[project]
name = "tg-quiz-bot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiogram>=3.25.0",
    "environs>=14.6.0",
    "redis>=7.2.0",
    "requests>=2.32.5",
    "vk-api>=11.10.0",
]
